name: "Practica GitHub Actions"

on:
  push:
    branches: ["main"]
    
    jobs:
  deploy-codigoTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests

      - name: Deploy to server
        run: |
          echo "Deploying to server..."
          # Aquí iría el comando para desplegar tu aplicación, por ejemplo:
          # scp -r . user@server:/path/to/deploy