name: Practica GitHub Actions

on:
  push:
    branches: ["main"]

jobs:
  deploy-codigoTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        run: echo "Hola, mundo!"
