name: Practica GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  deploy-codigoTest:
    runs-on: ubuntu-latest

    env:
      name: Deploy Codigo Test
    # This is a comment
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        
      - name: Saludo
        run: echo "Hola, mundo 1! $name"

        
        
        
  second_job:
          if: ${{ github.ref == 'refs/heads/main' }}
          needs: deploy-codigoTest
          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Saludo
              run: echo "Hola, mundo 2! ${{ github.ref }}"  
