name: Practica GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  deploy-codigoTest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        
      - name: Saludo
        run: echo "Hola, mundo 1!"

        
        
        
  second_job:
          needs: deploy-codigoTest
          runs-on: ubuntu-latest
          steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Saludo
              run: echo "Hola, mundo 2!"  
