name: Practica GitHub Actions

on:
  push:
    branches: [ main ]

jobs:
  deploy-codigoTest:
    runs-on: ubuntu-latest

    outputs:
      my_variable: ${{ steps.step_1.outputs.my_variable }} 
      #define output variable
    # This is a comment

    env:
      name: Deploy Codigo Test
    # This is a comment
      # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    steps:
      
      - name: working dir
        run: ls -al 


      - name: Checkout code
        uses: actions/checkout@v4

      
      - name: working dir after action
        run: ls -al
        
      
      - name: Saludo
        run: echo "Hola, mundo 1! $name"
        

      - name: working
        id: step_1
        run: echo "my_variable=hola zzz" >> $GITHUB_OUTPUT
#se crea una variable de salida que se puede usar en otros jobs
        # echo "my_variable=hola zzz" >> $GITHUB_OUTPUT
        # echo "my_variable=hola zzz" >> $GITHUB_ENV
        #se define una variable de salida que se puede usar en otros jobs
      - name: obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable }}"
     

        
        
        
  second_job:

          if: ${{ github.ref == 'refs/heads/main' }}
          needs: deploy-codigoTest
          runs-on: ubuntu-latest

          env:
            my_variable: ${{ needs.deploy-codigoTest.outputs.my_variable }} #se obtiene la variable de salida del job anterior
          # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          steps:

           - name: mi variable
             run: echo "my_variable"

           - name: Checkout code
             uses: actions/checkout@v4


           - name: Saludo
             run: echo "Hola, mundo 2! ${{ github.ref }}"  
