name: deploy to server 

on: push 

jobs:
    first-job:
      runs-on: ubuntu-latest
      
      strategy:
        fail-fast: false
        matrix:
          os: [ubuntu-latest, windows-latest, macos-latest]
          node-version: [14, 16, 18]